#!/bin/bash  
#SBATCH --job-name="ned"  
#SBATCH --output="ned.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 48:00:00

module load boost/1.55.0
module load intel/2015.2.164
module load mvapich2_ib

/home/rbarnes1/dist_flats/parallel_flats.exe /oasis/scratch/comet/rbarnes1/temp_project/ned/filled/ned_tiles.layout                               101  /oasis/scratch/comet/rbarnes1/temp_project/temp/ned-%f.tif /oasis/scratch/comet/rbarnes1/temp_project/ned_output/%f-d8.tif noflip
