export CXX=g++
export GDAL_LIBS=`gdal-config --libs`
export GDAL_CFLAGS=`gdal-config --cflags`
export CXXFLAGS=$(GDAL_CFLAGS) --std=c++11 -O3

#-DNOPROGRESS -DNDEBUG # -Wno-unknown-pragmas

include makefile.vars